[general]
; Температура экрана днем и ночью (в Кельвинах)
temp-day=6500
temp-night=3500

; Плавный переход (1 - да, 0 - нет)
fade=1

; Метод настройки (для Hyprland/Wayland используется wayland)
adjustment-method=wayland

; Источник координат
location-provider=manual

[manual]
; Координаты (взяты из вашего виджета погоды)
lat=59.34
lon=27.28
